[project]
name = "karen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.14.4",
    "dotenv>=0.9.9",
    "huggingface-hub>=1.23.0",
    "mcp>=1.28.0,<2.0.0",
    "numpy>=2.5.1",
    "onnxruntime>=1.18.0",
    "opencv-python>=4.10.0",
    "piper>=0.15.1",
    "piper-tts>=1.4.2",
    "plotext>=5.3.2",
    "pygame>=2.6.1",
    "pytesseract>=0.3.13",
    "requests>=2.32.0",
]
